### ISSUE TITLE
jsonschema for analysis scope configuration (i.e., `sigrid.yaml`)

### ISSUE THREAD

**Issue by AldoHennink** [Software-Improvement-Group/sigridci#147]
It would be a huge help to have a [jsonschema](https://json-schema.org/) for the analysis scope configuration file. It could validate the config files of users, without having to upload it through a CI.
I have placed an incomplete jsonschema below (note that it's actually formatted in Yaml).

Perhaps it could just be placed in the `softwareimprovementgroup/sigridci` Docker image,
with an extra command line option for `sigridci.py`, so that users could run

```sh
sigridci.py --validate-analysis-scope  my_sigrid.yaml
```

This also helps with the documentation, since you can never forget to list an option.

**Bonus tip**: multiple python packages (e.g., [dataclasses-jsonschema](https://pypi.org/project/dataclasses-jsonschema/))
will generate Python object that correspond to the jsonschema, so there is much less to code.

```yaml
$schema: http://json-schema.org/draft-04/schema#
type: object
properties:
   components:
      type: array
      items:
      -  type: object
         required: [name, include]
         properties:
            name:
               type: string
            include:
               type: array
               items:
               -  type: string
   languages:
      type: array
      items:
      -  type: object
         required: [name]
         properties:
            name:
               type: string
   dependencychecker:
      type: object
      required: [blacklist]
      properties:
         blacklist:
            type: array
            items:
            -  type: string
   alerts:
      type: object
      required: [enabled, recipients]
      properties:
         enabled:
            type: boolean
         recipients:
            type: array
            items:
            -  type: string
required:
- components
- languages
- alerts
# dependencychecker is not required
```
