### ISSUE TITLE
Create docker container for use in pipelines

### ISSUE THREAD

**Issue by oliv3r** [Software-Improvement-Group/sigridci#31]
Downloading files from github is a little bit odd, and shouldn't be done as general process. While the URL's can be modified to target specific hashes (and thus releases) it means the runner:
* Needs access to github
* Needs to have tools to download these files (wget/curl or worse, even git)
* Needs to have python available (apparently)
* Needs to know about other dependencies
* Needs to have the ability to install files onto the runner (usually, users do not have access)
* Needs to make the repo 'dirty' by adding untracked files (or needs the .gitignore to ignore something unknown to the code, `sigridci`.

Instead, SigridCI should be deployed (in addition to if you will) as a (minimal/alpine based) docker container.

As (modern) runners generally rely fully on containerization, this is not that odd. This would allow, the sigrid CI container to supply ALL dependencies and behave the same expected way, always, the CI file would be simplified.

For example for gitlab-ci.yml it would look as:
```yaml
stages:  
(...)
- report

(...)

sigridci:
  stage: report
  image: "registry.gitlab.com/Software-Improvement-Group/sigridci:latest"
  script:
    - sigridci.py --customer examplecustomername --system examplesystemname --source . --targetquality 3.5
  allow_failure: true
  artifacts:
    paths:
      - "sigrid-ci-output/*"
    expire_in: 1 week
    when: always
```

The container should adhere to the docker best practices of course, e.g. it should be able to run the python script upon launch, using a docker-entry point etc. (https://github.com/docker-library/official-images#consistency). Note for CI's a basic 'shell' is needed, as the runner will try to execute /bin/sh by default before running the script.
